{
  "uid" : "381a00221e3d3020",
  "name" : "test_stake_pool_metadata_no_description",
  "fullName" : "cardano_node_tests.tests.test_pools.TestNegative#test_stake_pool_metadata_no_description",
  "historyId" : "e38cd2a19fa75514c0d61d23b04b6d17",
  "time" : {
    "start" : 1604696761236,
    "stop" : 1604696761250,
    "duration" : 14
  },
  "description" : "Test pool metadata that is missing the 'description' key.",
  "descriptionHtml" : "<p>Test pool metadata that is missing the 'description' key.</p>\n",
  "status" : "failed",
  "statusMessage" : "Failed: Errors found in cluster log files:\n/home/martink/Source/repos/cardano-node-tests2/.artifacts/pytest-3-ccoeemek/popen-gw7/cluster_artifacts_bpokzefc/bft1.stdout: \u001B[31m[bender-3:cardano.node.LocalErrorPolicy:Error:41]\u001B[0m [2020-11-06 15:56:39.37 UTC] [String \"ErrorPolicyUnhandledApplicationException (Refused NodeToClientV_3 \\\"version data mismatch: NodeToClientVersionData {networkMagic = NetworkMagic {unNetworkMagic = 42}} /= NodeToClientVersionData {networkMagic = NetworkMagic {unNetworkMagic = 764824073}}\\\")\",String \"ErrorPolicyTrace\",String \"LocalAddress {getFilePath = \\\"\\\"}\"]",
  "statusTrace" : "self = <allure_commons._allure.fixture object at 0x7fd440227f40>, args = (), kwargs = {}\n\n    def __call__(self, *args, **kwargs):\n        self.parameters = func_parameters(self._fixture_function, *args, **kwargs)\n    \n        with self:\n>           return self._fixture_function(*args, **kwargs)\n\n/home/martink/.local/python_venvs/cardano_node/lib64/python3.8/site-packages/allure_commons/_allure.py:185: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/home/martink/Source/repos/cardano-node-tests2/cardano_node_tests/tests/conftest.py:100: in cluster_cleanup\n    _run_cluster_cleanup(\n/home/martink/Source/repos/cardano-node-tests2/cardano_node_tests/tests/conftest.py:68: in _run_cluster_cleanup\n    devops_cluster.process_artifacts(pytest_tmp_dir=pytest_tmp_dir, request=request)\n/home/martink/Source/repos/cardano-node-tests2/cardano_node_tests/utils/devops_cluster.py:293: in process_artifacts\n    report_artifacts_errors(errors)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nerrors = [(PosixPath('/home/martink/Source/repos/cardano-node-tests2/.artifacts/pytest-3-ccoeemek/popen-gw7/cluster_artifacts_b...rkMagic {unNetworkMagic = 764824073}}\\\\\")\",String \"ErrorPolicyTrace\",String \"LocalAddress {getFilePath = \\\\\"\\\\\"}\"]\\n')]\n\n    def report_artifacts_errors(errors: List[Tuple[Path, str]]) -> None:\n        \"\"\"Report errors found in artifacts.\"\"\"\n        err = [f\"{e[0]}: {e[1]}\" for e in errors]\n        err_joined = \"\\n\".join(err)\n>       pytest.fail(f\"Errors found in cluster log files:\\n{err_joined}\")\nE       Failed: Errors found in cluster log files:\nE       /home/martink/Source/repos/cardano-node-tests2/.artifacts/pytest-3-ccoeemek/popen-gw7/cluster_artifacts_bpokzefc/bft1.stdout: \u001B[31m[bender-3:cardano.node.LocalErrorPolicy:Error:41]\u001B[0m [2020-11-06 15:56:39.37 UTC] [String \"ErrorPolicyUnhandledApplicationException (Refused NodeToClientV_3 \\\"version data mismatch: NodeToClientVersionData {networkMagic = NetworkMagic {unNetworkMagic = 42}} /= NodeToClientVersionData {networkMagic = NetworkMagic {unNetworkMagic = 764824073}}\\\")\",String \"ErrorPolicyTrace\",String \"LocalAddress {getFilePath = \\\"\\\"}\"]\n\n/home/martink/Source/repos/cardano-node-tests2/cardano_node_tests/utils/devops_cluster.py:278: Failed",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "worker_id",
    "time" : {
      "start" : 1604676882863,
      "stop" : 1604676882863,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "cluster_manager",
    "time" : {
      "start" : 1604696761235,
      "stop" : 1604696761235,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "cluster",
    "time" : {
      "start" : 1604696761235,
      "stop" : 1604696761235,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "change_dir",
    "time" : {
      "start" : 1604676882862,
      "stop" : 1604676882863,
      "duration" : 1
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "session_autouse",
    "time" : {
      "start" : 1604676882864,
      "stop" : 1604676882864,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "cluster_cleanup",
    "time" : {
      "start" : 1604676882863,
      "stop" : 1604676882863,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "tmp_path_factory",
    "time" : {
      "start" : 1604676882862,
      "stop" : 1604676882862,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "temp_dir",
    "time" : {
      "start" : 1604695951420,
      "stop" : 1604695951420,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "testStage" : {
    "description" : "Test pool metadata that is missing the 'description' key.",
    "status" : "failed",
    "statusMessage" : "Failed: Errors found in cluster log files:\n/home/martink/Source/repos/cardano-node-tests2/.artifacts/pytest-3-ccoeemek/popen-gw7/cluster_artifacts_bpokzefc/bft1.stdout: \u001B[31m[bender-3:cardano.node.LocalErrorPolicy:Error:41]\u001B[0m [2020-11-06 15:56:39.37 UTC] [String \"ErrorPolicyUnhandledApplicationException (Refused NodeToClientV_3 \\\"version data mismatch: NodeToClientVersionData {networkMagic = NetworkMagic {unNetworkMagic = 42}} /= NodeToClientVersionData {networkMagic = NetworkMagic {unNetworkMagic = 764824073}}\\\")\",String \"ErrorPolicyTrace\",String \"LocalAddress {getFilePath = \\\"\\\"}\"]",
    "statusTrace" : "self = <allure_commons._allure.fixture object at 0x7fd440227f40>, args = (), kwargs = {}\n\n    def __call__(self, *args, **kwargs):\n        self.parameters = func_parameters(self._fixture_function, *args, **kwargs)\n    \n        with self:\n>           return self._fixture_function(*args, **kwargs)\n\n/home/martink/.local/python_venvs/cardano_node/lib64/python3.8/site-packages/allure_commons/_allure.py:185: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/home/martink/Source/repos/cardano-node-tests2/cardano_node_tests/tests/conftest.py:100: in cluster_cleanup\n    _run_cluster_cleanup(\n/home/martink/Source/repos/cardano-node-tests2/cardano_node_tests/tests/conftest.py:68: in _run_cluster_cleanup\n    devops_cluster.process_artifacts(pytest_tmp_dir=pytest_tmp_dir, request=request)\n/home/martink/Source/repos/cardano-node-tests2/cardano_node_tests/utils/devops_cluster.py:293: in process_artifacts\n    report_artifacts_errors(errors)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nerrors = [(PosixPath('/home/martink/Source/repos/cardano-node-tests2/.artifacts/pytest-3-ccoeemek/popen-gw7/cluster_artifacts_b...rkMagic {unNetworkMagic = 764824073}}\\\\\")\",String \"ErrorPolicyTrace\",String \"LocalAddress {getFilePath = \\\\\"\\\\\"}\"]\\n')]\n\n    def report_artifacts_errors(errors: List[Tuple[Path, str]]) -> None:\n        \"\"\"Report errors found in artifacts.\"\"\"\n        err = [f\"{e[0]}: {e[1]}\" for e in errors]\n        err_joined = \"\\n\".join(err)\n>       pytest.fail(f\"Errors found in cluster log files:\\n{err_joined}\")\nE       Failed: Errors found in cluster log files:\nE       /home/martink/Source/repos/cardano-node-tests2/.artifacts/pytest-3-ccoeemek/popen-gw7/cluster_artifacts_bpokzefc/bft1.stdout: \u001B[31m[bender-3:cardano.node.LocalErrorPolicy:Error:41]\u001B[0m [2020-11-06 15:56:39.37 UTC] [String \"ErrorPolicyUnhandledApplicationException (Refused NodeToClientV_3 \\\"version data mismatch: NodeToClientVersionData {networkMagic = NetworkMagic {unNetworkMagic = 42}} /= NodeToClientVersionData {networkMagic = NetworkMagic {unNetworkMagic = 764824073}}\\\")\",String \"ErrorPolicyTrace\",String \"LocalAddress {getFilePath = \\\"\\\"}\"]\n\n/home/martink/Source/repos/cardano-node-tests2/cardano_node_tests/utils/devops_cluster.py:278: Failed",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "9b8f8954582e324a",
      "name" : "log",
      "source" : "9b8f8954582e324a.txt",
      "type" : "text/plain",
      "size" : 581
    } ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 1,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  },
  "afterStages" : [ {
    "name" : "cluster_manager::0",
    "time" : {
      "start" : 1604696761251,
      "stop" : 1604696761252,
      "duration" : 1
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "cluster_cleanup::0",
    "time" : {
      "start" : 1604696761253,
      "stop" : 1604696766263,
      "duration" : 5010
    },
    "status" : "failed",
    "statusMessage" : "Failed: Errors found in cluster log files:\n/home/martink/Source/repos/cardano-node-tests2/.artifacts/pytest-3-ccoeemek/popen-gw7/cluster_artifacts_bpokzefc/bft1.stdout: \u001B[31m[bender-3:cardano.node.LocalErrorPolicy:Error:41]\u001B[0m [2020-11-06 15:56:39.37 UTC] [String \"ErrorPolicyUnhandledApplicationException (Refused NodeToClientV_3 \\\"version data mismatch: NodeToClientVersionData {networkMagic = NetworkMagic {unNetworkMagic = 42}} /= NodeToClientVersionData {networkMagic = NetworkMagic {unNetworkMagic = 764824073}}\\\")\",String \"ErrorPolicyTrace\",String \"LocalAddress {getFilePath = \\\"\\\"}\"]\n\n",
    "statusTrace" : "  File \"/home/martink/.local/python_venvs/cardano_node/lib64/python3.8/site-packages/allure_commons/_allure.py\", line 185, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/home/martink/.local/python_venvs/cardano_node/lib64/python3.8/site-packages/_pytest/fixtures.py\", line 926, in _teardown_yield_fixture\n    next(it)\n  File \"/home/martink/Source/repos/cardano-node-tests2/cardano_node_tests/tests/conftest.py\", line 100, in cluster_cleanup\n    _run_cluster_cleanup(\n  File \"/home/martink/Source/repos/cardano-node-tests2/cardano_node_tests/tests/conftest.py\", line 68, in _run_cluster_cleanup\n    devops_cluster.process_artifacts(pytest_tmp_dir=pytest_tmp_dir, request=request)\n  File \"/home/martink/Source/repos/cardano-node-tests2/cardano_node_tests/utils/devops_cluster.py\", line 293, in process_artifacts\n    report_artifacts_errors(errors)\n  File \"/home/martink/Source/repos/cardano-node-tests2/cardano_node_tests/utils/devops_cluster.py\", line 278, in report_artifacts_errors\n    pytest.fail(f\"Errors found in cluster log files:\\n{err_joined}\")\n  File \"/home/martink/.local/python_venvs/cardano_node/lib64/python3.8/site-packages/_pytest/outcomes.py\", line 153, in fail\n    raise Failed(msg=msg, pytrace=pytrace)\n",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  }, {
    "name" : "temp_dir::0",
    "time" : {
      "start" : 1604696761252,
      "stop" : 1604696761252,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "tag",
    "value" : "@pytest.mark.usefixtures('temp_dir')"
  }, {
    "name" : "parentSuite",
    "value" : "cardano_node_tests.tests"
  }, {
    "name" : "suite",
    "value" : "test_pools"
  }, {
    "name" : "subSuite",
    "value" : "TestNegative"
  }, {
    "name" : "host",
    "value" : "bender-3900x"
  }, {
    "name" : "thread",
    "value" : "372812-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "cardano_node_tests.tests.test_pools"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ {
    "name" : "https://github.com/input-output-hk/cardano-node-tests/blob/2469c31cf82ae27863e9c0f51580385f1471d017/cardano_node_tests/tests/test_pools.py#L1528",
    "url" : "https://github.com/input-output-hk/cardano-node-tests/blob/2469c31cf82ae27863e9c0f51580385f1471d017/cardano_node_tests/tests/test_pools.py#L1528",
    "type" : "link"
  } ],
  "hidden" : true,
  "retry" : true,
  "extra" : {
    "categories" : [ ],
    "tags" : [ "@pytest.mark.usefixtures('temp_dir')" ]
  },
  "source" : "381a00221e3d3020.json",
  "parameterValues" : [ ]
}