{"uuid": "4c8f60f1-29b1-4e6d-bb2f-b04b9b4d0f77", "children": ["030868c1-31f7-42e5-a0ca-3efe9cb9fb6e", "a953b7eb-07b4-462d-8142-89ca03c571c4", "0a5b907f-5cc6-446c-b076-9c2b3a4626ad", "53352ef3-4785-422e-9410-36ea1f7baad2", "649d9ddc-66d4-4951-a086-cf34832c7dba", "c14181af-04fd-43e4-b30e-68ff79e04b9b", "df8cdea0-0960-48b1-9943-3a686137bb15", "a5fcbd83-a8ef-4777-a60a-4b6703b16d75", "b26f8c4f-3b16-4c31-bbe4-5a5e6859189c", "5c4a1835-382b-40ed-8bba-00e586ad16ea", "fd2b9210-ed69-46a3-b474-dd511c053484", "1e2dea13-57b2-44aa-b1ab-1bc67cf220c3", "6f9101ee-8a34-4eee-8042-a4e5d6a66ae6", "8889f51d-9a6d-4fab-9775-a25c1bae6c23", "afb4d9c7-04e9-4a3a-a325-d1eb21a031e5", "f5f3be71-cc38-43ce-98e7-d11d585f2280", "6cf74fc6-cd6a-4afe-9dd0-dc7350776a56", "390b0f09-8e27-4020-9df7-08420febc22d", "514a2681-ca04-4626-9289-2b3121387256", "45e38d22-acc4-4409-8a77-638403bd30d8", "6c7c1cb3-a7e8-4590-98e4-7596f48b382a", "290c7f63-f3c9-4033-93db-4a4d38905cee"], "befores": [{"name": "cluster_cleanup", "status": "passed", "start": 1604310980588, "stop": 1604310980588}], "afters": [{"name": "cluster_cleanup::0", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '/home/martink/Source/repos/cardano-node-tests2/tmp/testrun_20201102.log'\n", "trace": "  File \"/home/martink/.local/python_venvs/cardano_node/lib64/python3.8/site-packages/allure_commons/_allure.py\", line 185, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/home/martink/.local/python_venvs/cardano_node/lib64/python3.8/site-packages/_pytest/fixtures.py\", line 926, in _teardown_yield_fixture\n    next(it)\n  File \"/home/martink/Source/repos/cardano-node-tests2/cardano_node_tests/tests/conftest.py\", line 100, in cluster_cleanup\n    _run_cluster_cleanup(\n  File \"/home/martink/Source/repos/cardano-node-tests2/cardano_node_tests/tests/conftest.py\", line 57, in _run_cluster_cleanup\n    cluster_manager_obj = parallel_run.ClusterManager(\n  File \"/home/martink/Source/repos/cardano-node-tests2/cardano_node_tests/utils/parallel_run.py\", line 67, in __init__\n    self.lock_log = self._init_log()\n  File \"/home/martink/Source/repos/cardano-node-tests2/cardano_node_tests/utils/parallel_run.py\", line 82, in _init_log\n    open(run_log, \"a\").close()\n"}, "start": 1604310980892, "stop": 1604310980943}], "start": 1604310980588, "stop": 1604310980943}