{"uuid": "17552b8e-13ab-498e-b256-7e8e97fb6212", "children": ["86558f8f-2190-43a9-b5fe-28df265a2990"], "befores": [{"name": "cluster_kes", "status": "broken", "statusDetails": {"message": "KeyboardInterrupt\n", "trace": "  File \"/home/martink/.local/python_venvs/cardano_node/lib64/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/martink/.local/python_venvs/cardano_node/lib64/python3.8/site-packages/_pytest/fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/martink/.local/python_venvs/cardano_node/lib64/python3.8/site-packages/_pytest/fixtures.py\", line 917, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/martink/Source/repos/cardano-node-tests2/cardano_node_tests/tests/test_kes.py\", line 57, in cluster_kes\n    return cluster_manager.get(singleton=True, cleanup=True, start_cmd=str(short_kes_start_cluster))\n  File \"/home/martink/Source/repos/cardano-node-tests2/cardano_node_tests/utils/parallel_run.py\", line 410, in get\n    self._restart(start_cmd=start_cmd)\n  File \"/home/martink/Source/repos/cardano-node-tests2/cardano_node_tests/utils/parallel_run.py\", line 142, in _restart\n    devops_cluster.setup_test_addrs(cluster_obj, tmp_path)\n  File \"/home/martink/Source/repos/cardano-node-tests2/cardano_node_tests/utils/devops_cluster.py\", line 145, in setup_test_addrs\n    clusterlib_utils.fund_from_genesis(\n  File \"/home/martink/Source/repos/cardano-node-tests2/cardano_node_tests/utils/clusterlib_utils.py\", line 125, in fund_from_genesis\n    cluster_obj.wait_for_new_block(new_blocks=2)\n  File \"/home/martink/Source/repos/cardano-node-tests2/cardano_node_tests/utils/clusterlib.py\", line 1354, in wait_for_new_block\n    time.sleep(self.slot_length)\n"}, "start": 1604493213060, "stop": 1604493227612}], "start": 1604493213060, "stop": 1604493227818}